# Generated by Django 3.2.4 on 2021-06-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.CharField(max_length=50, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='stories/', verbose_name='Превью')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('start_date', models.DateTimeField(verbose_name='Дата старта')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('orderNum', models.IntegerField(verbose_name='Приоритет сториса')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storyApp.project')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'Истории',
            },
        ),
        migrations.CreateModel(
            name='StoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moreDetailedUrl', models.SlugField(max_length=160)),
                ('moreDetailedText', models.CharField(max_length=250)),
                ('contentType', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('content', models.TextField(verbose_name='Контент')),
                ('duration', models.TimeField(default=15)),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала сториса')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания сториса')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storyApp.story')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subs_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_watched', models.BooleanField(default=False)),
                ('watch_date', models.DateTimeField(verbose_name='Просмотр')),
                ('storyFile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storyApp.storyfile')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='storyApp.subscriber')),
            ],
        ),
    ]
