# Generated by Django 3.2.4 on 2021-06-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyfile',
            options={'verbose_name': 'Файл истории', 'verbose_name_plural': 'Файлы истории'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AlterModelOptions(
            name='userstoryfile',
            options={'verbose_name': 'Файл истории пользователя', 'verbose_name_plural': 'Файлы истории пользователя'},
        ),
        migrations.AlterField(
            model_name='story',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storyApp.project', verbose_name='проект'),
        ),
        migrations.AlterField(
            model_name='storyfile',
            name='duration',
            field=models.TimeField(default=15, verbose_name='Время показа'),
        ),
        migrations.AlterField(
            model_name='storyfile',
            name='moreDetailedText',
            field=models.CharField(max_length=250, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='storyfile',
            name='moreDetailedUrl',
            field=models.SlugField(max_length=160, verbose_name='Путь к файлам'),
        ),
    ]
